### ISSUE TITLE
Avoid biome doesn't work

### ISSUE THREAD

**Issue by PureVanillaFrance** [kadenscott/Quantum#19]
Hi ! when I try to avoid biome with spawn I get the following error : 

.... [19:40:18 WARN]: [QuantumAPI] Plugin QuantumAPI v1.4.3 generated an exception while executing task 249
java.lang.IllegalStateException: ChunkSnapshot created without biome. Please call getSnapshot with includeBiome=true
at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.16.5.jar:git-Paper-585]
at org.bukkit.craftbukkit.v1_16_R3.CraftChunkSnapshot.getBiome(CraftChunkSnapshot.java:130) ~[patched_1.16.5.jar:git-Paper-585]
at dev.kscott.quantum.rule.rules.async.OnlyBiomeRule.validate(OnlyBiomeRule.java:53) ~[?:?]
at dev.kscott.quantum.location.LocationProvider.lambda$validateLocation$8(LocationProvider.java:269) ~[?:?]
at dev.kscott.quantum.dependencies.commandframework.bukkit.BukkitSynchronizer.lambda$runAsynchronous$3(BukkitSynchronizer.java:80) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-585]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-585]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-585]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]

run latest paper.

Thanks for your help !

**Comment by PureVanillaFrance** [comment]
I am on Java11

**Comment by webcrawls** [comment]
Could you please provide me with the output of /version, along with what Quantum plugins you're using (i.e. QuantumSpawn, QuantumAPI) and their versions? Thanks.
